# Generated by Django 6.0.3 on 2026-04-07 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.pessoa')),
                ('funcao', models.CharField(help_text='Função na empresa', max_length=35, verbose_name='Função')),
                ('data_admissao', models.DateField(help_text='Data de admissão na empresa', verbose_name='Admissão')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
            bases=('clientes.pessoa',),
        ),
    ]
