# Generated by Django 6.0.3 on 2026-03-24 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fornecedores',
            new_name='Fornecedor',
        ),
    ]
