# Generated by Django 6.0.3 on 2026-05-05 23:09

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_rename_fornecedores_fornecedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': [django.db.models.functions.text.Upper('nome')], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
