# Generated by Django 6.0.3 on 2026-05-04 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('servicos', '0004_alter_produtosservico_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('A', 'Agendado'), ('R', 'Realizado'), ('C', 'Cancelado')], default='A', max_length=1, verbose_name='Situação')),
                ('observacoes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Preço')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_servicos_funcionario', to='agendamentos.agendamento', verbose_name='Agendamento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordem_servicos_servico', to='servicos.servico', verbose_name='Serviçoo')),
            ],
            options={
                'verbose_name': 'Serviço realizado',
                'verbose_name_plural': 'Serviços realizados',
                'constraints': [models.UniqueConstraint(fields=('agendamento', 'servico'), name='constraint_servico')],
            },
        ),
    ]
