# Generated by Django 6.0.3 on 2026-05-05 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_ordemservico'),
        ('funcionarios', '0001_initial'),
        ('servicos', '0004_alter_produtosservico_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('A', 'Agendado'), ('R', 'Realizado'), ('C', 'Cancelado')], default='A', max_length=1, verbose_name='Situação')),
                ('observacoes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Serviço realizado',
                'verbose_name_plural': 'Serviços realizados',
            },
        ),
        migrations.RemoveConstraint(
            model_name='ordemservico',
            name='constraint_servico',
        ),
        migrations.AddField(
            model_name='ordemservicos',
            name='agendamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_servicos_agendamento', to='agendamentos.agendamento', verbose_name='Agendamento'),
        ),
        migrations.AddField(
            model_name='ordemservicos',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordem_servicos_funcionario', to='funcionarios.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AddField(
            model_name='ordemservicos',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordem_servicos_servico', to='servicos.servico', verbose_name='Serviçoo'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servicos',
            field=models.ManyToManyField(through='agendamentos.OrdemServicos', to='servicos.servico', verbose_name='Serviço'),
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='agendamento',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='servico',
        ),
        migrations.AddConstraint(
            model_name='ordemservicos',
            constraint=models.UniqueConstraint(fields=('agendamento', 'servico'), name='constraint_agendamento'),
        ),
        migrations.DeleteModel(
            name='OrdemServico',
        ),
    ]
