# Generated by Django 6.0.3 on 2026-05-05 23:09

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_ordemservicos_remove_ordemservico_constraint_servico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': [django.db.models.functions.text.Upper('horario')], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(default='A', help_text='Status', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor total'),
        ),
    ]
