# Generated by Django 6.0.3 on 2026-05-06 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_alter_agendamento_options_agendamento_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-horario'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
    ]
