# Generated by Django 6.0.3 on 2026-04-27 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quantidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_servico_produto', to='produtos.produto', verbose_name='Produto')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_servico_servico', to='servicos.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Produto utilizado',
                'verbose_name_plural': 'Produtos utilizados',
            },
        ),
    ]
