# Generated by Django 6.0.3 on 2026-04-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('servicos', '0002_produtosservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='produtos',
            field=models.ManyToManyField(related_name='servco_produtos', through='servicos.ProdutosServico', to='produtos.produto'),
        ),
    ]
