# Generated by Django 6.0.3 on 2026-04-28 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('servicos', '0003_servico_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosservico',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_servico_produto', to='produtos.produto', verbose_name='Produto'),
        ),
    ]
