# Generated by Django 6.0.3 on 2026-05-05 23:09

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_alter_produtosservico_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': [django.db.models.functions.text.Upper('nome')], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
    ]
