# Generated by Django 6.0.3 on 2026-05-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_options'),
        ('servicos', '0005_alter_servico_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='produtosservico',
            constraint=models.UniqueConstraint(fields=('servico', 'produto'), name='constraint_servico_produto'),
        ),
    ]
